const constants = {
    ADD_CASE: 'ADD_CASE',
    SELECTED_CASE: 'SELECTED_CASE',
    NAME_CASE: 'NAME_CASE',
    REMOVE_CASE: 'REMOVE_CASE', 
    COMPLETE_CASE: 'COMPLETE_CASE',
    PRIORITY_CASE: 'PRIORITY_CASE',
    SORT_CASE: 'SORT_CASE',
    SETTINGS_CASE: 'SETTINGS_CASE',
    CHANGE_NOTE: 'CHANGE_NOTE',
    CHANGE_SUBTASKS: 'CHANGE_SUBTASKS'

}
export default constants